### ISSUE TITLE
[Bug] Refreshing Results Returns to Feature

### ISSUE THREAD

**Issue by luuuk** [mackenzieleach/screwthereview#63]

**Comment by mackenzieleach** [comment]
On the results page, if a user hits "refresh", they are immediately taken back to Search or Roulette (depending on the feature they had used to get the result). Ideally, if a user presses the refresh button, this should only reload the same experience result for them, rather than sending them back to Search/Roulette.

**Comment by mackenzieleach** [comment]
Switching this to low priority since this doesn't affect core functionality and there's other issues we'd prefer to tackle first that have more impact on functionality.
